version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      target: development
    environment:
      - NODE_ENV=development
      - PORT=5173
      - HOST=0.0.0.0
      - DATABASE_URL=mysql://root:example@db:3306/demo
      - JWT_ACCESS_SECRET=secret
    ports:
      - 5173:5173
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./svelte.config.js:/app/svelte.config.js
      - ./prisma:/app/prisma
      # - .:/app
      # - app_svelte_node_modules:/app/node_modules
    depends_on:
      db:
        condition: service_healthy
    # working_dir: /home/node/app
    command: npm run dev -- --host
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 'example'
      MYSQL_DATABASE: 'demo'
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    entrypoint: sh
    command: -c "/opt/bin/minio server /export --address :9000 --console-address :9001"
    volumes:
      - ./docker/minio/data:/export
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db

volumes:
  mysql_data:
  app_svelte_node_modules:
