/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArticleCreate
 */
export interface ArticleCreate {
    /**
     * 
     * @type {string}
     * @memberof ArticleCreate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCreate
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCreate
     */
    authorId: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCreate
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCreate
     */
    filename: string;
    /**
     * 
     * @type {boolean}
     * @memberof ArticleCreate
     */
    allowExternal: boolean;
    /**
     * 
     * @type {string}
     * @memberof ArticleCreate
     */
    showFrom: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleCreate
     */
    showUntil: string;
    /**
     * 
     * @type {boolean}
     * @memberof ArticleCreate
     */
    reviewOk: boolean;
}

/**
 * Check if a given object implements the ArticleCreate interface.
 */
export function instanceOfArticleCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "content" in value;
    isInstance = isInstance && "authorId" in value;
    isInstance = isInstance && "path" in value;
    isInstance = isInstance && "filename" in value;
    isInstance = isInstance && "allowExternal" in value;
    isInstance = isInstance && "showFrom" in value;
    isInstance = isInstance && "showUntil" in value;
    isInstance = isInstance && "reviewOk" in value;

    return isInstance;
}

export function ArticleCreateFromJSON(json: any): ArticleCreate {
    return ArticleCreateFromJSONTyped(json, false);
}

export function ArticleCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'],
        'authorId': json['author_id'],
        'path': json['path'],
        'filename': json['filename'],
        'allowExternal': json['allow_external'],
        'showFrom': json['show_from'],
        'showUntil': json['show_until'],
        'reviewOk': json['review_ok'],
    };
}

export function ArticleCreateToJSON(value?: ArticleCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'content': value.content,
        'author_id': value.authorId,
        'path': value.path,
        'filename': value.filename,
        'allow_external': value.allowExternal,
        'show_from': value.showFrom,
        'show_until': value.showUntil,
        'review_ok': value.reviewOk,
    };
}

