/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArticleUpdate
 */
export interface ArticleUpdate {
    /**
     * 
     * @type {string}
     * @memberof ArticleUpdate
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleUpdate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleUpdate
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleUpdate
     */
    authorId: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleUpdate
     */
    path: string | null;
    /**
     * 
     * @type {string}
     * @memberof ArticleUpdate
     */
    filename: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ArticleUpdate
     */
    allowExternal: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ArticleUpdate
     */
    showFrom: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ArticleUpdate
     */
    showUntil: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof ArticleUpdate
     */
    reviewOk: boolean | null;
}

/**
 * Check if a given object implements the ArticleUpdate interface.
 */
export function instanceOfArticleUpdate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "authorId" in value;
    isInstance = isInstance && "path" in value;
    isInstance = isInstance && "filename" in value;
    isInstance = isInstance && "allowExternal" in value;
    isInstance = isInstance && "showFrom" in value;
    isInstance = isInstance && "showUntil" in value;
    isInstance = isInstance && "reviewOk" in value;

    return isInstance;
}

export function ArticleUpdateFromJSON(json: any): ArticleUpdate {
    return ArticleUpdateFromJSONTyped(json, false);
}

export function ArticleUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'authorId': json['author_id'],
        'path': json['path'],
        'filename': json['filename'],
        'allowExternal': json['allow_external'],
        'showFrom': (json['show_from'] === null ? null : new Date(json['show_from'])),
        'showUntil': (json['show_until'] === null ? null : new Date(json['show_until'])),
        'reviewOk': json['review_ok'],
    };
}

export function ArticleUpdateToJSON(value?: ArticleUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'description': value.description,
        'author_id': value.authorId,
        'path': value.path,
        'filename': value.filename,
        'allow_external': value.allowExternal,
        'show_from': (value.showFrom === null ? null : value.showFrom.toISOString()),
        'show_until': (value.showUntil === null ? null : value.showUntil.toISOString()),
        'review_ok': value.reviewOk,
    };
}

