/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdventCalendarResponse
 */
export interface AdventCalendarResponse {
    /**
     * 
     * @type {string}
     * @memberof AdventCalendarResponse
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof AdventCalendarResponse
     */
    year: number;
    /**
     * 
     * @type {string}
     * @memberof AdventCalendarResponse
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof AdventCalendarResponse
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof AdventCalendarResponse
     */
    authorId: string;
}

/**
 * Check if a given object implements the AdventCalendarResponse interface.
 */
export function instanceOfAdventCalendarResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "year" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "authorId" in value;

    return isInstance;
}

export function AdventCalendarResponseFromJSON(json: any): AdventCalendarResponse {
    return AdventCalendarResponseFromJSONTyped(json, false);
}

export function AdventCalendarResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdventCalendarResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'year': json['year'],
        'title': json['title'],
        'description': json['description'],
        'authorId': json['author_id'],
    };
}

export function AdventCalendarResponseToJSON(value?: AdventCalendarResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'year': value.year,
        'title': value.title,
        'description': value.description,
        'author_id': value.authorId,
    };
}

