/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdventCalendarArticleCreate
 */
export interface AdventCalendarArticleCreate {
    /**
     * 
     * @type {string}
     * @memberof AdventCalendarArticleCreate
     */
    adventCalendarId: string;
    /**
     * 
     * @type {number}
     * @memberof AdventCalendarArticleCreate
     */
    day: number;
    /**
     * 
     * @type {string}
     * @memberof AdventCalendarArticleCreate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof AdventCalendarArticleCreate
     */
    articleId: string;
    /**
     * 
     * @type {string}
     * @memberof AdventCalendarArticleCreate
     */
    authorId: string;
}

/**
 * Check if a given object implements the AdventCalendarArticleCreate interface.
 */
export function instanceOfAdventCalendarArticleCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "adventCalendarId" in value;
    isInstance = isInstance && "day" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "articleId" in value;
    isInstance = isInstance && "authorId" in value;

    return isInstance;
}

export function AdventCalendarArticleCreateFromJSON(json: any): AdventCalendarArticleCreate {
    return AdventCalendarArticleCreateFromJSONTyped(json, false);
}

export function AdventCalendarArticleCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdventCalendarArticleCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'adventCalendarId': json['advent_calendar_id'],
        'day': json['day'],
        'title': json['title'],
        'articleId': json['article_id'],
        'authorId': json['author_id'],
    };
}

export function AdventCalendarArticleCreateToJSON(value?: AdventCalendarArticleCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'advent_calendar_id': value.adventCalendarId,
        'day': value.day,
        'title': value.title,
        'article_id': value.articleId,
        'author_id': value.authorId,
    };
}

