/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReviewCreate
 */
export interface ReviewCreate {
    /**
     * 
     * @type {string}
     * @memberof ReviewCreate
     */
    comment: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewCreate
     */
    reviewerId: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewCreate
     */
    articleId: string;
}

/**
 * Check if a given object implements the ReviewCreate interface.
 */
export function instanceOfReviewCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "comment" in value;
    isInstance = isInstance && "reviewerId" in value;
    isInstance = isInstance && "articleId" in value;

    return isInstance;
}

export function ReviewCreateFromJSON(json: any): ReviewCreate {
    return ReviewCreateFromJSONTyped(json, false);
}

export function ReviewCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'comment': json['comment'],
        'reviewerId': json['reviewer_id'],
        'articleId': json['article_id'],
    };
}

export function ReviewCreateToJSON(value?: ReviewCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'comment': value.comment,
        'reviewer_id': value.reviewerId,
        'article_id': value.articleId,
    };
}

