/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReviewUpdate
 */
export interface ReviewUpdate {
    /**
     * 
     * @type {string}
     * @memberof ReviewUpdate
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewUpdate
     */
    comment: string;
    /**
     * 
     * @type {boolean}
     * @memberof ReviewUpdate
     */
    approved: boolean;
}

/**
 * Check if a given object implements the ReviewUpdate interface.
 */
export function instanceOfReviewUpdate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "comment" in value;
    isInstance = isInstance && "approved" in value;

    return isInstance;
}

export function ReviewUpdateFromJSON(json: any): ReviewUpdate {
    return ReviewUpdateFromJSONTyped(json, false);
}

export function ReviewUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'comment': json['comment'],
        'approved': json['approved'],
    };
}

export function ReviewUpdateToJSON(value?: ReviewUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'comment': value.comment,
        'approved': value.approved,
    };
}

